### PR TITLE
Adds new translations: Spanish (Spain) and Basque

### PR DESCRIPTION
**Pull request by IngrownMink4**
I added two new files:
 
- es.po (Spanish translation)
- eu.po (Basque translation)

### CODE REVIEW

**Comment by alexkdeveloper** [comment]
Hi!
The LINGUAS file should also display the suggested translations, otherwise they will not work. 

I only see the translation of the application description. There is no translation of the interface and messages. Are you planning to supplement the translation?

**Comment by IngrownMink4** [comment]
> Hi! The LINGUAS file should also display the suggested translations, otherwise they will not work.
> 
> I only see the translation of the application description. There is no translation of the interface and messages. Are you planning to supplement the translation?

Hi. I took the `it.po` file from @albanobattistella and changed the Italian text to Spanish and Basque. In which file are the text strings of the interface and messages? Regarding LINGUAS, I'll add it right away.

**Comment by alexkdeveloper** [comment]
The necessary lines are in the window.vala

**Comment by IngrownMink4** [comment]
> The necessary lines are in the window.vala

Found it. I'll now finish what remains to be translated. Thank you.

**Comment by IngrownMink4** [comment]
Everything should be fine now.

**Pull request merged**
